language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5"

services:
  - docker

env:
  - MEMCACHED_PASS=kljfdsKLJDF2093

before_install:
  - docker pull tutum/memcached
  - docker run -d -p 11212:11211 -e MEMCACHED_PASS="$MEMCACHED_PASS" tutum/memcached

after_script: make test-coveralls

sudo: required
